/*Data for the table `settings` */
INSERT  INTO `settings`(`company_id`,`type`,`field1`,`field2`,`field3`,`field4`,`remarks`,`created_at`,`updated_at`) VALUES
(NULL,'venue_settings',NULL,'{\"from_pos\":true}',NULL,NULL,NULL,NULL,NULL),
(NULL,'configure_numbers','0',NULL,NULL,NULL,NULL,'2020-02-11 15:49:35','2020-02-17 11:20:35'),
(NULL,'voucher_code_length','9',NULL,NULL,NULL,NULL,NULL,'2020-02-18 05:45:38'),
(NULL,'billing_on_off','0','[]',NULL,NULL,NULL,'2020-02-18 10:28:21','2020-03-04 09:58:19'),
(NULL,'Demographic Criteria','segment','[{\"name\":\"allUsers\",\"show\":true,\"fieldName\":\"All Users\"},{\"name\":\"gender\",\"show\":true,\"fieldName\":\"Gender\"},{\"name\":\"date_of_birth\",\"show\":true,\"fieldName\":\"Age\"},{\"name\":\"birth_day\",\"show\":true,\"fieldName\":\"Birthday\"},{\"name\":\"postal_code\",\"show\":true,\"fieldName\":\"Postcode\"}]',NULL,NULL,NULL,NULL,'2020-03-10 10:41:57'),
(NULL,'Membership Criteria','segment','[{\"name\":\"creation_datetime\",\"show\":true,\"fieldName\":\"Membership Join Date\"},{\"name\":\"membership_number\",\"show\":true,\"fieldName\":\"Membership Number\"},{\"name\":\"last_login\",\"show\":true,\"fieldName\":\"Last Login\"},{\"name\":\"reffering_users\",\"show\":true,\"fieldName\":\"Referring user\"},{\"name\":\"reffered_user\",\"show\":true,\"fieldName\":\"Referred User\"},{\"name\":\"member_group\",\"show\":true,\"fieldName\":\"Member Group\"},{\"name\":\"user_source\",\"show\":true,\"fieldName\":\"Source\"},{\"name\":\"last_transaction\",\"show\":true,\"fieldName\":\"Last Transaction\"},{\"name\":\"total_spending\",\"show\":true,\"fieldName\":\"Total Spending\"},{\"name\":\"average_basket_value\",\"show\":true,\"fieldName\":\"Average Basket Value\"},{\"name\":\"spender_percentage\",\"show\":true,\"fieldName\":\"Spender (%)\"},{\"name\":\"user_activity\",\"show\":true,\"fieldName\":\"Activity\"},{\"name\":\"gap_map_users\",\"show\":true,\"fieldName\":\"Gap Map\"},{\"name\":\"enter_venue\",\"show\":true,\"fieldName\":\"Enter Site\"},{\"name\":\"default_venue\",\"show\":true,\"fieldName\":\"Default Site\"},{\"name\":\"member_group\",\"show\":true,\"fieldName\":\"Member Group\"},{\"name\":\"target_users\",\"show\":true,\"fieldName\":\"Target Users\"},{\"name\":\"user_region\",\"show\":true,\"fieldName\":\"User Region\"},{\"name\":\"gap_map_users\",\"show\":true,\"fieldName\":\"Never Transacted Customers\"},{\"name\":\"venue_store_name\",\"show\":true,\"fieldName\":\"Store Name\"}]',NULL,NULL,NULL,NULL,'2020-03-10 05:53:27'),
(NULL,'Promotion Criteria','segment','[{\"name\":\"voucher_expiry\",\"show\":true,\"fieldName\":\"Voucher Expiry\"},{\"name\":\"voucher_status\",\"show\":true,\"fieldName\":\"Voucher Status\"},{\"name\":\"punch_card_status\",\"show\":true,\"fieldName\":\"Punch Card Status\"},{\"name\":\"token_not_used\",\"show\":true,\"fieldName\":\"Token Not Used\"},{\"name\":\"token_used_in_charity\",\"show\":true,\"fieldName\":\"Token Used in Charity\"},{\"name\":\"token_used\",\"show\":true,\"fieldName\":\"Token Used\"},{\"name\":\"completed_survey\",\"show\":true,\"fieldName\":\"Completed Survey\"},{\"name\":\"seen_videos\",\"show\":true,\"fieldName\":\"Seen Videos\"},{\"name\":\"campaign_triggers\",\"show\":true,\"fieldName\":\"Campaign Triggers\"}]',NULL,NULL,NULL,NULL,NULL),
(NULL,'Mission Criteria','segment','[{\"name\":\"scan_qr_code\",\"show\":true,\"fieldName\":\"Scan QR Code\"},{\"name\":\"user_sign_up\",\"show\":true,\"fieldName\":\"Sign Up\"},{\"name\":\"user_gps_detect\",\"show\":true,\"fieldName\":\"GPS\"},{\"name\":\"user_optional_field\",\"show\":true,\"fieldName\":\"Optional Fields Filling\"},{\"name\":\"transaction_amount\",\"show\":true,\"fieldName\":\"Transaction Amount\"},{\"name\":\"referral_user\",\"show\":true,\"fieldName\":\"Referred User\"}]',NULL,NULL,NULL,NULL,NULL);